@startuml

title __PERSISTENCE's Class Diagram__\n

  namespace test.nz.ac.vuw.ecs.swen225.gp20.persistence {
    class test.nz.ac.vuw.ecs.swen225.gp20.persistence.PersistenceTest {
        - fileName : String
        {static} + saveFile()
        + test_Load_01_Wall()
        + test_Load_02_FreeTile()
        + test_Load_03_FreeTile()
        + test_Load_04_FreeTile()
        + test_Load_05_FreeTile()
        + test_Load_06_FreeTile()
        + test_Load_07_LockedDoor()
        + test_Load_08_ExitLock()
        + test_Load_09_Exit()
        + test_Load_10_Water()
        + test_Load_11_Ice()
        + test_Load_12_InfoTile()
        + test_Load_13_Conveyor()
        + test_Load_14_Vent()
        + test_Load_15_Player()
        + test_Load_16_Player()
        + test_Load_17_Enemy()
        + test_Load_18_Enemy()
        + test_Load_19_Enemy()
        + test_Load_20_Floor()
        + test_Save_01_Wall()
        + test_Save_02_FreeTile()
        + test_Save_03_FreeTile()
        + test_Save_04_FreeTile()
        + test_Save_05_FreeTile()
        + test_Save_06_FreeTile()
        + test_Save_07_LockedDoor()
        + test_Save_08_ExitLock()
        + test_Save_09_Exit()
        + test_Save_10_Water()
        + test_Save_11_Ice()
        + test_Save_12_InfoTile()
        + test_Save_13_Conveyor()
        + test_Save_14_Vent()
        + test_Save_15_Player()
        + test_Save_16_Player()
        + test_Save_17_Enemy()
        + test_Save_18_Enemy()
        + test_Save_19_Enemy()
        + test_Save_20_Floor()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
