@startuml

title __APPLICATION's Class Diagram__\n

  namespace nz.ac.vuw.ecs.swen225.gp20.application {
    class nz.ac.vuw.ecs.swen225.gp20.application.ApplicationView {
        - countdownTimer : Timer
        - currSpeed : double
        - gameOver : boolean
        - help : JMenu
        - helpWindow : JLabel
        - isPaused : boolean
        - isReplay : boolean
        - load : JMenu
        - loadGame : JMenuItem
        - loadReplay : JMenuItem
        - lowerWindow : JPanel
        - mainWindow : JPanel
        - npcMovementTimer : Timer
        - replayPath : String
        - replaySpeed : JLabel
        - replays : JMenu
        - save : JMenu
        - saveGame : JMenuItem
        - saveReplay : JMenuItem
        - scoreCount : JLabel
        - viewHelp : JMenuItem
        - window : JFrame
        + ApplicationView()
        + ApplicationView()
        + changeLevel()
        + disposeWindow()
        + getLevelPath()
        + getMain()
        + loadReplay()
        + makeReplayDialog()
        + playerMovement()
        + restartLevel()
        + startTimers()
        + stopTimers()
        - addToWindow()
        - changeReplaySpeed()
        - loadSave()
        - makeWindow()
        - saveGame()
        - showHelpView()
        - showLoadReplayDialogue()
        - showSaveReplayDialogue()
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.application {
    class nz.ac.vuw.ecs.swen225.gp20.application.BackgroundPanel {
        - background : Image
        + BackgroundPanel()
        + paintComponent()
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.application {
    class nz.ac.vuw.ecs.swen225.gp20.application.HelpView {
        + HelpView()
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.application {
    class nz.ac.vuw.ecs.swen225.gp20.application.InventoryPanel {
        - background : Image
        + InventoryPanel()
        + paintComponent()
        - drawInventory()
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.application {
    class nz.ac.vuw.ecs.swen225.gp20.application.LevelLostView {
        - owner : JFrame
        - timeOut : boolean
        + LevelLostView()
        - addToDialog()
        - setupWindow()
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.application {
    class nz.ac.vuw.ecs.swen225.gp20.application.LevelWonView {
        - owner : JFrame
        + LevelWonView()
        - addToDialog()
        - setupWindow()
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.application {
    class nz.ac.vuw.ecs.swen225.gp20.application.Main {
        + currLevel : int
        + deface : Font
        + levelPath : String
        + loadReplayLevel()
        + loadSave()
        {static} + main()
        + nextLevel()
        + restartLevel()
        - Main()
        - quickLoad()
        - setup()
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.application {
    class nz.ac.vuw.ecs.swen225.gp20.application.ReplayDoneView {
        - owner : JFrame
        + ReplayDoneView()
        - addToDialog()
        - setupWindow()
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.application {
    class nz.ac.vuw.ecs.swen225.gp20.application.SetupView {
        - dialog : JDialog
        - mainPanel : JPanel
        - panes : CardLayout
        + SetupView()
        - addToDialog()
        - setupWindow()
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.application {
    class nz.ac.vuw.ecs.swen225.gp20.application.SmallSave {
        + SmallSave()
        {static} + loadFile()
        {static} + removeFile()
        {static} + saveFile()
    }
  }
  

  nz.ac.vuw.ecs.swen225.gp20.application.ApplicationView o-- nz.ac.vuw.ecs.swen225.gp20.application.Main : game
  nz.ac.vuw.ecs.swen225.gp20.application.ApplicationView o-- nz.ac.vuw.ecs.swen225.gp20.application.HelpView : helpView
  nz.ac.vuw.ecs.swen225.gp20.application.ApplicationView o-- nz.ac.vuw.ecs.swen225.gp20.recnplay.Replay : log
  nz.ac.vuw.ecs.swen225.gp20.application.ApplicationView o-- nz.ac.vuw.ecs.swen225.gp20.maze.Maze : maze
  nz.ac.vuw.ecs.swen225.gp20.application.ApplicationView o-- nz.ac.vuw.ecs.swen225.gp20.render.Board : viewport
  nz.ac.vuw.ecs.swen225.gp20.application.BackgroundPanel -up-|> javax.swing.JPanel
  nz.ac.vuw.ecs.swen225.gp20.application.HelpView -up-|> javax.swing.JDialog
  nz.ac.vuw.ecs.swen225.gp20.application.InventoryPanel -up-|> javax.swing.JPanel
  nz.ac.vuw.ecs.swen225.gp20.application.InventoryPanel o-- nz.ac.vuw.ecs.swen225.gp20.maze.Maze : maze
  nz.ac.vuw.ecs.swen225.gp20.application.LevelLostView o-- nz.ac.vuw.ecs.swen225.gp20.application.ApplicationView : game
  nz.ac.vuw.ecs.swen225.gp20.application.LevelWonView o-- nz.ac.vuw.ecs.swen225.gp20.application.ApplicationView : game
  nz.ac.vuw.ecs.swen225.gp20.application.Main o-- nz.ac.vuw.ecs.swen225.gp20.application.ApplicationView : game
  nz.ac.vuw.ecs.swen225.gp20.application.ReplayDoneView o-- nz.ac.vuw.ecs.swen225.gp20.application.ApplicationView : game
  nz.ac.vuw.ecs.swen225.gp20.application.SetupView o-- nz.ac.vuw.ecs.swen225.gp20.application.Main : game


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
