@startuml

title __ELEMENTS's Class Diagram__\n

  namespace nz.ac.vuw.ecs.swen225.gp20.recnplay {
    namespace elements {
      class nz.ac.vuw.ecs.swen225.gp20.recnplay.elements.Action {
          ~ action : String
          ~ character : String
          ~ timeSinceLastMove : long
          + Action()
          + play()
          + writeHistory()
          - calcMove()
      }
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.recnplay {
    namespace elements {
      class nz.ac.vuw.ecs.swen225.gp20.recnplay.elements.Level {
          ~ levelName : String
          - actions : ArrayList<Action>
          + Level()
          + actionCount()
          + addAction()
          + equals()
          + hashCode()
          + play()
          + writeHistory()
      }
    }
  }
  

  namespace nz.ac.vuw.ecs.swen225.gp20.recnplay {
    namespace elements {
      class nz.ac.vuw.ecs.swen225.gp20.recnplay.elements.Node {
          ~ levels : ArrayList<Level>
          + Node()
          + play()
          - parseActions()
          - parseLevels()
      }
    }
  }
  

  nz.ac.vuw.ecs.swen225.gp20.recnplay.elements.Action .up.|> nz.ac.vuw.ecs.swen225.gp20.recnplay.interfaces.Play
  nz.ac.vuw.ecs.swen225.gp20.recnplay.elements.Action .up.|> nz.ac.vuw.ecs.swen225.gp20.recnplay.interfaces.Save
  nz.ac.vuw.ecs.swen225.gp20.recnplay.elements.Level .up.|> nz.ac.vuw.ecs.swen225.gp20.recnplay.interfaces.Play
  nz.ac.vuw.ecs.swen225.gp20.recnplay.elements.Level .up.|> nz.ac.vuw.ecs.swen225.gp20.recnplay.interfaces.Save
  nz.ac.vuw.ecs.swen225.gp20.recnplay.elements.Node .up.|> nz.ac.vuw.ecs.swen225.gp20.recnplay.interfaces.Play


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
